# Site settings
title:            MC-GT07-IFCINT
description:      Fiches d'échanges openBIM point à point
keywords:         ...
author:           Alexandre Grignon
url:              "http://mc-gt07-ifcint.bimstandards.fr"
repository:       alexandregrignon/MC-GT07-IFCINT

# Versions
version:          alpha.1
latest_update:    07/03/2017

# Build settings
markdown:         kramdown
highlighter:      rouge
exclude:          [vendor]

# Collections
collections:
  pages: {output: true, permalink: '/:path/'}
  fiches: {output: true, permalink: '/fiches/:path/'}
  
# Assets
sass:
  style: compressed
cdn:
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

# Gems (Jekyll plugins)
gems:
  - jekyll-sitemap
  - jekyll-github-metadata

# Pour activer github-metadata : https://github.com/jekyll/github-metadata
# $ JEKYLL_GITHUB_TOKEN=123abc [bundle exec] jekyll serve
